sonar.organization=seed-drill
sonar.projectKey=cordelia-node
sonar.projectName=cordelia-node

sonar.sources=crates/
sonar.tests=crates/
sonar.test.inclusions=**/tests/**,**/*test*/**
sonar.coverage.reportPaths=coverage.lcov

sonar.sourceEncoding=UTF-8
