#!/bin/bash
# Generate Docker Compose + configs for S3 PAN (swarm) test.
# Usage: generate-s3.sh [swarm_per_lead]
#
# Topology: 1 bootnode + 2 relays + 2 leads + N swarm per lead = 5 + 2*N containers
# Networks: 1 internet + 2 home zones (one per lead)
#
# Lead identity keys are pre-generated so swarm nodes can derive child
# identities at container init time (§8.2.2).
#
# IP scheme:
#   Internet (172.29.0.0/24):
#     172.29.0.10       bootnode
#     172.29.0.20-21    relays
#     172.29.0.30-31    leads (also on home zones)
#   Home zone Z (172.28.Z.0/24):
#     172.28.Z.30       lead-Z
#     172.28.Z.40-4N    swarm-Z-{0..N-1}

set -euo pipefail

SWARM_PER_LEAD=${1:-4}
LEADS=2
RELAYS=2
BOOTNODES=1
SWARM_TOTAL=$((LEADS * SWARM_PER_LEAD))
CONTAINER_COUNT=$((BOOTNODES + RELAYS + LEADS + SWARM_TOTAL))

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT_DIR="$SCRIPT_DIR/s3-${SWARM_PER_LEAD}"
COMPOSE="$OUT_DIR/s3-${SWARM_PER_LEAD}.yml"
CONFIG_DIR="$OUT_DIR/configs"
KEY_DIR="$OUT_DIR/keys"

mkdir -p "$CONFIG_DIR" "$KEY_DIR"

echo "Generating S3-${SWARM_PER_LEAD}: ${BOOTNODES}B + ${RELAYS}R + ${LEADS}L + ${SWARM_TOTAL}S = ${CONTAINER_COUNT} nodes"
echo "  ${SWARM_PER_LEAD} swarm nodes per lead"

# ── Pre-generate lead identity keys ──────────────────────────────────
# Swarm nodes need the lead's seed at init time to derive child identities.
# Generate 32-byte random seeds and write as identity.key files.

for i in $(seq 0 $((LEADS - 1))); do
    key_file="$KEY_DIR/lead-${i}.identity.key"
    if [ ! -f "$key_file" ]; then
        dd if=/dev/urandom bs=32 count=1 of="$key_file" 2>/dev/null
        chmod 600 "$key_file"
        echo "  Generated lead-${i} identity key"
    fi
done

# ── Node configs ─────────────────────────────────────────────────────

BOOTNODE_ADDR="172.29.0.10:9474"

# Bootnode
cat > "$CONFIG_DIR/b1.toml" << TOML
[identity]
entity_id = "b1_test"
[node]
http_port = 9473
p2p_port = 9474
data_dir = "/data/cordelia"
[network]
listen_addr = "0.0.0.0:9474"
role = "bootnode"
allow_private_addresses = true
dns_discovery = ""
bootnodes = []
[governor]
hot_min = 10
hot_max = 20
warm_min = 5
warm_max = 30
cold_max = 50
tick_interval_secs = 2
[replication]
sync_interval_realtime_secs = 5
[logging]
level = "debug"
TOML

# Relays
for i in $(seq 0 $((RELAYS - 1))); do
    name="r$((i + 1))"
    cat > "$CONFIG_DIR/${name}.toml" << TOML
[identity]
entity_id = "${name}_test"
[node]
http_port = 9473
p2p_port = 9474
data_dir = "/data/cordelia"
[network]
listen_addr = "0.0.0.0:9474"
role = "relay"
allow_private_addresses = true
dns_discovery = ""
[[network.bootnodes]]
addr = "$BOOTNODE_ADDR"
[governor]
hot_min = 5
hot_max = 10
warm_min = 3
warm_max = 20
cold_max = 50
tick_interval_secs = 2
[replication]
sync_interval_realtime_secs = 5
[logging]
level = "debug"
TOML
done

# Leads: personal nodes that accept swarm inbound via HKDF verification
for i in $(seq 0 $((LEADS - 1))); do
    name="lead-${i}"
    cat > "$CONFIG_DIR/${name}.toml" << TOML
[identity]
entity_id = "${name}_test"
[node]
http_port = 9473
p2p_port = 9474
data_dir = "/data/cordelia"
[network]
listen_addr = "0.0.0.0:9474"
role = "personal"
allow_private_addresses = true
dns_discovery = ""
[[network.bootnodes]]
addr = "$BOOTNODE_ADDR"
[governor]
hot_min = 2
hot_max = 2
warm_min = 3
warm_max = 10
cold_max = 50
tick_interval_secs = 2
[replication]
sync_interval_realtime_secs = 5
[logging]
level = "debug"
TOML
done

# Swarm nodes: personal nodes, connect only to their lead
# Config sets swarm fields; entrypoint detects CORDELIA_SWARM_INDEX env
# and runs swarm-init instead of regular init.
for l in $(seq 0 $((LEADS - 1))); do
    lead_addr="172.28.${l}.30:9474"
    for s in $(seq 0 $((SWARM_PER_LEAD - 1))); do
        name="swarm-${l}-${s}"
        # Swarm nodes need bootnodes pointing to their lead (for outbound connection)
        cat > "$CONFIG_DIR/${name}.toml" << TOML
[identity]
entity_id = "${name}_test"
[node]
http_port = 9473
p2p_port = 9474
data_dir = "/data/cordelia"
[network]
listen_addr = "0.0.0.0:9474"
role = "personal"
allow_private_addresses = true
dns_discovery = ""
[[network.bootnodes]]
addr = "${lead_addr}"
[governor]
hot_min = 1
hot_max = 1
warm_min = 1
warm_max = 3
cold_max = 10
tick_interval_secs = 2
[replication]
sync_interval_realtime_secs = 5
[logging]
level = "debug"
[swarm]
swarm_index = ${s}
lead_identity_path = "/keys/lead.identity.key"
lead_entity_id = "lead-${l}_test"
TOML
    done
done

# ── Docker Compose ───────────────────────────────────────────────────

cat > "$COMPOSE" << 'HEADER'
# S3 PAN (swarm) test topology -- generated by generate-s3.sh
# DO NOT EDIT -- regenerate with generate-s3.sh

services:
HEADER

# Bootnode service
cat >> "$COMPOSE" << EOF
  b1:
    image: cordelia-test:latest
    command: ["cordelia", "--config", "/data/cordelia/config.toml", "start"]
    volumes:
      - ./configs/b1.toml:/config/config.toml:ro
    networks:
      internet:
        ipv4_address: 172.29.0.10
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:9473/api/v1/health"]
      interval: 5s
      timeout: 3s
      retries: 6
      start_period: 15s

EOF

# Relay services
for i in $(seq 0 $((RELAYS - 1))); do
    name="r$((i + 1))"
    ip="172.29.0.$((20 + i))"
    cat >> "$COMPOSE" << EOF
  ${name}:
    image: cordelia-test:latest
    command: ["cordelia", "--config", "/data/cordelia/config.toml", "start"]
    volumes:
      - ./configs/${name}.toml:/config/config.toml:ro
    networks:
      internet:
        ipv4_address: ${ip}
    depends_on:
      b1:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:9473/api/v1/health"]
      interval: 5s
      timeout: 3s
      retries: 6
      start_period: 15s

EOF
done

# Lead services (internet + home zone)
# Mount pre-generated identity key so it's used during init
for i in $(seq 0 $((LEADS - 1))); do
    name="lead-${i}"
    inet_ip="172.29.0.$((30 + i))"
    home_ip="172.28.${i}.30"
    cat >> "$COMPOSE" << EOF
  ${name}:
    image: cordelia-test:latest
    command: ["cordelia", "--config", "/data/cordelia/config.toml", "start"]
    volumes:
      - ./configs/${name}.toml:/config/config.toml:ro
      - ./keys/${name}.identity.key:/keys/lead.identity.key:ro
    networks:
      internet:
        ipv4_address: ${inet_ip}
      zone-${i}:
        ipv4_address: ${home_ip}
    depends_on:
      b1:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:9473/api/v1/health"]
      interval: 5s
      timeout: 3s
      retries: 6
      start_period: 15s

EOF
done

# Swarm services (home zone only)
# Mount lead's identity key + set env vars for swarm-init
for l in $(seq 0 $((LEADS - 1))); do
    for s in $(seq 0 $((SWARM_PER_LEAD - 1))); do
        name="swarm-${l}-${s}"
        home_ip="172.28.${l}.$((40 + s))"
        cat >> "$COMPOSE" << EOF
  ${name}:
    image: cordelia-test:latest
    command: ["cordelia", "--config", "/data/cordelia/config.toml", "start"]
    environment:
      CORDELIA_SWARM_INDEX: "${s}"
      CORDELIA_LEAD_IDENTITY: "/keys/lead.identity.key"
      CORDELIA_LEAD_ENTITY_ID: "lead-${l}_test"
    volumes:
      - ./configs/${name}.toml:/config/config.toml:ro
      - ./keys/lead-${l}.identity.key:/keys/lead.identity.key:ro
    networks:
      zone-${l}:
        ipv4_address: ${home_ip}
    depends_on:
      lead-${l}:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:9473/api/v1/health"]
      interval: 5s
      timeout: 3s
      retries: 6
      start_period: 15s

EOF
    done
done

# Networks
cat >> "$COMPOSE" << 'EOF'
networks:
  internet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/24
EOF

for i in $(seq 0 $((LEADS - 1))); do
    cat >> "$COMPOSE" << EOF
  zone-${i}:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.${i}.0/24
EOF
done

echo ""
echo "Generated: $COMPOSE"
echo "  Containers: $CONTAINER_COUNT"
echo "  Configs: $CONFIG_DIR/"
echo "  Lead keys: $KEY_DIR/"
echo ""
echo "Run with: bash $SCRIPT_DIR/run-s3.sh $SWARM_PER_LEAD"
